version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: '15:00'
      timezone: Africa/Ceuta

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '10:00'
      timezone: Africa/Ceuta
